#!/usr/bin/env python3
"""Convert CachyOS Ananicy classifications to System76 Scheduler KDL.

The generated file intentionally carries names and coarse classifications
only. Ananicy's daemon-specific nice, scheduler, OOM, and cgroup policy is not
copied, and ananicy-cpp must not run alongside this integration.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PROFILE_BY_TYPE = {
    "Game": "games",
    "LowLatency_RT": "foreground",
    "Player-Audio": "foreground",
    "Player-Video": "foreground",
    "Image-View": "foreground",
    "Doc-View": "foreground",
    "Chat": "foreground",
    "Launcher": "background",
    "Service": "session-services",
    "Heavy_CPU": "batch",
    "BG_CPU": "batch",
    "BG_CPUIO": "batch",
    "IN_DIFF": "background",
}

# Prefer latency-sensitive classifications when an upstream name is repeated.
PROFILE_PRIORITY = {
    "foreground": 5,
    "games": 4,
    "session-services": 3,
    "background": 2,
    "batch": 1,
}

# Some upstream desktop rules intentionally carry direct nice values instead of
# an Ananicy type. Keep a tiny Meo-owned classification for the shell processes
# that must remain latency-sensitive; no upstream scheduler policy is copied.
CORE_DESKTOP_PROFILES = {
    "plasmashell": "foreground",
    "kwin_wayland": "foreground",
    "kwin_x11": "foreground",
    "krunner": "foreground",
    "baloo_file": "batch",
    "baloo_file_extractor": "batch",
}


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def classifications(source: Path) -> dict[str, set[str]]:
    selected: dict[str, str] = dict(CORE_DESKTOP_PROFILES)
    for rule_file in sorted(source.rglob("*.rules")):
        for raw_line in rule_file.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw_line.strip().removesuffix("+")
            if not line or line.startswith("#"):
                continue
            try:
                rule = json.loads(line)
            except json.JSONDecodeError:
                continue
            name = str(rule.get("name", "")).strip()
            profile = PROFILE_BY_TYPE.get(str(rule.get("type", "")))
            if not name or not profile or "\x00" in name or len(name) > 255:
                continue
            previous = selected.get(name)
            if previous is None or PROFILE_PRIORITY[profile] > PROFILE_PRIORITY[previous]:
                selected[name] = profile

    result = {profile: set() for profile in PROFILE_PRIORITY}
    for name, profile in selected.items():
        result[profile].add(name)
    return result


def render(source: Path, revision: str) -> str:
    groups = classifications(source)
    count = sum(map(len, groups.values()))
    lines = [
        "// Generated by MeoKDE tools/system/compile-ananicy-rules.py.",
        "// Classification source: https://github.com/CachyOS/ananicy-rules",
        f"// Source revision: {revision}",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Classification data only; this does not install or run Ananicy.",
        f"// Unique process names: {count}",
        "assignments {",
    ]
    for profile in ("foreground", "games", "session-services", "background", "batch"):
        lines.append(f"    {profile} {{")
        lines.extend(f"        {quoted(name)}" for name in sorted(groups[profile], key=str.casefold))
        lines.append("    }")
        lines.append("")
    lines.extend(["}", "", "exceptions {", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--revision", required=True)
    args = parser.parse_args()
    if not args.source.is_dir():
        parser.error(f"rules directory does not exist: {args.source}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.source, args.revision), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
