[Icon Theme]
Name=Meo Symbols
Comment=Material Symbols Rounded system icon theme for Meo Desktop
Inherits=breeze,hicolor
Example=folder
FollowsColorScheme=false
Directories=scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/emblems,scalable/emotes,scalable/mimetypes,scalable/places,scalable/status,scalable/panel,symbolic/actions,symbolic/devices,symbolic/places,symbolic/status

[scalable/actions]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Actions


[scalable/apps]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Applications


[scalable/categories]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Categories


[scalable/devices]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Devices


[scalable/emblems]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Emblems


[scalable/emotes]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Emotes


[scalable/mimetypes]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=MimeTypes


[scalable/places]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Places


[scalable/status]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Status


[scalable/panel]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Status


[symbolic/actions]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Actions


[symbolic/devices]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Devices


[symbolic/places]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Places


[symbolic/status]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Status
