[Metadata]
Name=Meo Input Method Light
Version=1
Author=Meo
Description=Material 3 light tonal candidate panel
ScaleWithDPI=True

[InputPanel]
NormalColor=#1c1b1f
HighlightColor=#ffffff
HighlightBackgroundColor=#6750a4
HighlightCandidateColor=#1d192b
CandidateLabelColor=#49454f
HighlightCandidateLabelColor=#1d192b
CandidateCommentColor=#49454f
HighlightCandidateCommentColor=#1d192b
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=8
Right=8
Top=8
Bottom=8

[InputPanel/ContentMargin]
Left=7
Right=7
Top=7
Bottom=7

[InputPanel/Background]
Image=panel.svg

[InputPanel/Background/Margin]
Left=24
Right=24
Top=24
Bottom=24

[InputPanel/Highlight]
Image=highlight.svg

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=8
Bottom=8

[InputPanel/PrevPage]
Image=prev.svg

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.svg

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#1c1b1f
HighlightCandidateColor=#21005d

[Menu/Background]
Image=panel.svg

[Menu/Background/Margin]
Left=24
Right=24
Top=24
Bottom=24

[Menu/ContentMargin]
Left=7
Right=7
Top=7
Bottom=7

[Menu/Highlight]
Image=menu-highlight.svg

[Menu/Highlight/Margin]
Left=8
Right=8
Top=8
Bottom=8

[Menu/Separator]
Color=#79747e

[Menu/CheckBox]
Image=check.svg

[Menu/SubMenu]
Image=submenu.svg

[Menu/TextMargin]
Left=8
Right=8
Top=8
Bottom=8
