[Icon Theme]
Name=Meo
Comment=MeoArch colour application icons with Material 3 system symbols
Inherits=Papirus,breeze,hicolor
Directories=scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/places,scalable/status

[scalable/actions]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Actions

[scalable/apps]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/categories]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Categories

[scalable/devices]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Devices

[scalable/places]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Places

[scalable/status]
Size=24
MinSize=16
MaxSize=64
Type=Scalable
Context=Status
